name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: developer-33  # Replace with your GitHub username
          outputs: dist/snake.svg

      - name: Upload the snake animation
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg

      - name: Push the animation to the GitHub repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Generated snake animation"
          git push
